# Generated by Django 3.1.4 on 2020-12-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FillMno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=10, verbose_name='城市名')),
                ('mno', models.CharField(help_text='请输出正确的机器编号', max_length=128, unique=True, verbose_name='机器编号')),
                ('mname', models.CharField(max_length=128, verbose_name='机器名称')),
                ('ct', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('mt', models.DateField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '补满机器',
                'verbose_name_plural': '补满机器管理',
            },
        ),
    ]
