# Generated by Django 3.1.4 on 2020-12-06 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wuliu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='员工名称不能重复', max_length=128, verbose_name='员工名称')),
                ('gender', models.IntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, verbose_name='性别')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='年龄')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('idCard', models.CharField(blank=True, help_text='请输出18位的身份证号码', max_length=18, null=True, verbose_name='身份证号')),
                ('birthday', models.DateField(verbose_name='出生日期')),
                ('status', models.IntegerField(choices=[(0, '在职'), (1, '请假'), (2, '离职')], default=0, verbose_name='状态')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '物流',
                'verbose_name_plural': '物流人员管理',
            },
        ),
    ]
